# Generated by Django 6.0.5 on 2026-08-12 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('canceled', 'Canceled')], default='booked', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Appointment.appointmentslot'),
        ),
    ]
