
"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
BASE_DIR=Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY=os.getenv("DJANGO_SECRET_KEY")

DEBUG=os.getenv("DJANGO_DEBUG","False").lower()=="true"

ALLOWED_HOSTS=[
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS","").split(",")
    if host.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'Accounts',
    'Appointment',
]
AUTH_USER_MODEL = "Accounts.CustomUser"

REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
        "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
        "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ),
        "DEFAULT_THROTTLE_RATES": {
        "anon": "20/min",
        "user": "300/hour",
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES={
    "default":{
        "ENGINE":"django.db.backends.postgresql",
        "NAME":os.getenv("DB_NAME"),
        "USER":os.getenv("DB_USER"),
        "PASSWORD":os.getenv("DB_PASSWORD"),
        "HOST":os.getenv("DB_HOST","127.0.0.1"),
        "PORT":os.getenv("DB_PORT","5432"),
    }
}




# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL="/static/"
STATIC_ROOT=BASE_DIR / "staticfiles"

MEDIA_URL="/media/"
MEDIA_ROOT=BASE_DIR / "media"

MAX_REPORT_FILE_SIZE = 2 * 1024 * 1024

ALLOWED_REPORT_EXTENSIONS = [
    ".pdf",
]




# ---------- Email ----------
EMAIL_BACKEND=os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST=os.getenv("EMAIL_HOST","smtp.gmail.com")
EMAIL_PORT=int(os.getenv("EMAIL_PORT","587"))
EMAIL_USE_TLS=os.getenv("EMAIL_USE_TLS","True").lower()=="true"
EMAIL_HOST_USER=os.getenv("EMAIL_HOST_USER","")
EMAIL_HOST_PASSWORD=os.getenv("EMAIL_HOST_PASSWORD","")
DEFAULT_FROM_EMAIL=os.getenv("DEFAULT_FROM_EMAIL",EMAIL_HOST_USER)

FRONTEND_URL=os.getenv("FRONTEND_URL","http://localhost:5173")
PASSWORD_RESET_TIMEOUT=3600

# Add these keys to DEFAULT_THROTTLE_RATES:
# "password_reset": "5/hour",
# "password_reset_confirm": "10/hour",
